language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
install:
    - virtualenv env
    - env/bin/pip install -U setuptools
    - env/bin/python bootstrap.py
    - bin/buildout -N
script:
    - bin/test -v1
notifications:
    email: false
